### ISSUE TITLE
llvm weirdness

### ISSUE THREAD

**Issue by mwotton** [mikeizbicki/typeparams#6]
Probably not directly the fault of this lib, but I had trouble installing until I downgraded to llvm-3.4.

```
 for i in llvm-config llvm-link llvm-as llvm-dis lli llc opt ; do sudo update-alternatives --install /usr/bin/$i $i /usr/bin/$i-3.4 34; done
```

original error

```
[1 of 8] Compiling Data.Params.PseudoPrim ( src/Data/Params/PseudoPrim.hs, dist/dist-sandbox-1935361b/build/Data/Params/PseudoPrim.o )
You are using a new version of LLVM that hasn't been tested yet!
We will try though...
Alias must point to a definition
i8* @"stg_ap_0_fast$alias"
Alias must point to a definition
```

**Comment by mikeizbicki** [comment]
This is embarassing that I didn't see this post until now.... I assume it's not relavent anymore, but each version of GHC has a specific version of LLVM that it requires, which is why this behavior happened.
